import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/src/components/ui/shadcn/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body
                className={`antialiased`}
            >
                {children}
                <Toaster position="top-right" />
            </body>
        </html>
    );
}
